name: CI

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]*"
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.platform-architecture[0] }}
    strategy:
      fail-fast: false
      matrix:
        platform-architecture:
          - [ubuntu-latest, manylinux, "x86_64"]
          - [ubuntu-24.04-arm, manylinux, "aarch64"]
          - [macos-15-intel, macosx, x86_64]
          - [macos-14, macosx, arm64]
#           - [windows-latest, win, amd64]
#           - [windows-11-arm, win, arm64]
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.22"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --no-install-project

      - name: Create a symlink to the pydust library
        if: ${{ matrix.platform-architecture[1] != 'win' }}
        run: |
            python -c 'import sysconfig; print(sysconfig.get_paths()["platlib"])'
            find .venv -type f -name ffi.h
            ln -sf .venv/lib/python${{ matrix.python-version }}/site-packages/pydust ./pydust
            ls -al ./pydust/src/ffi.h

      - name: Create a symlink to the pydust library (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
            call .venv\Scripts\activate
            for /f "delims=" %%i in ('python -c "import sysconfig; print(sysconfig.get_paths()[\"platlib\"]) "') do set PLATLIB=%%i
            echo Using platlib: %PLATLIB%
            dir "%PLATLIB%"

            mklink /D pydust "%PLATLIB%\pydust"
            dir pydust

      - name: Poetry Build
        run: |
            uv run poetry build -v
            ls -al ./dist

      - name: Ruff check
        run: uv run ruff check .

      - name: Ruff format
        run: uv run ruff format --check .

      - name: Pytest
        run: uv run pytest test

      # We generate nice stubs manually.
      #- name: Check stubs
      #  run: uv run python -m ziglang build generate-stubs -Dcheck-stubs=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}-${{ matrix.platform-architecture[1] }}-${{ matrix.platform-architecture[2] }}
          path: ./dist/*.whl
          if-no-files-found: error

  upload:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Display structure of downloaded files
        run: ls -lh dist

#       - uses: pypa/gh-action-pypi-publish@release/v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           skip-existing: true
#           user: ${{ secrets.PYPI_USERNAME }}
#           password: ${{ secrets.PYPI_PASSWORD }}
